{
  "hash": "9ca6622e32892b7284f42fe675b237e1",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Day 02: Bouncing Ball Physics 🏀\"\nsubtitle: \"Discover the Magic of Velocity and Gravity!\"\nauthor: \"Pygame Tutorial Series\"\nformat:\n  html:\n    theme: light\n    toc: true\n    toc-depth: 3\n    code-copy: true\n    css: ../../shared/styles/tutorial.css\nexecute:\n  enabled: true\n  cache: false\n---\n\n::: {.hero-banner}\n# 🏀 Welcome to Day 02!\n\nToday, you'll create a **physics simulation** with bouncing balls! You'll learn about velocity, acceleration, gravity, and friction. By the end of this tutorial, you'll have balls bouncing realistically around your screen!\n\n**Time Required:** ~45 minutes  \n**Difficulty:** Beginner 🌟\n:::\n\n---\n\n## 🎯 What You'll Learn Today\n\nBy the end of this tutorial, you will be able to:\n\n- ✅ Understand **velocity** and **acceleration**\n- ✅ Implement **gravity** in your games\n- ✅ Create **realistic bouncing** with energy loss\n- ✅ Work with **multiple objects** at once\n- ✅ Add **interactive elements** (spawn balls with mouse clicks)\n\n---\n\n## 📚 Quick Recap: What We Learned in Day 01\n\nYesterday, we covered:\n- Setting up a Pygame project with UV\n- Creating game windows and the game loop\n- Handling keyboard input\n- Basic collision detection\n\nToday builds on these concepts with physics!\n\n---\n\n## 🎓 Part 1: Understanding Physics in Games (10 minutes)\n\n### What is Velocity?\n\n**Velocity** describes how fast something is moving and in what direction.\n\n- **Horizontal velocity (vx)**: How fast something moves left/right\n- **Vertical velocity (vy)**: How fast something moves up/down\n\n::: {.callout-note}\n## 🎯 What This Code Demonstrates\n\nThis example shows how **velocity changes position over time**. We'll:\n1. Create an object at position (100, 100)\n2. Give it velocity: moving right (+5) and up (-3) each frame\n3. Update its position 5 times and watch it move!\n\n**Key idea:** Position changes by velocity amount every frame. After 5 frames with vx=5, the object moves 25 pixels right!\n:::\n\n::: {#f43e7618 .cell execution_count=1}\n``` {.python .cell-code}\n# Let's explore velocity!\n# Think of velocity as \"how many pixels to move each frame\"\n\nclass SimpleObject:\n    def __init__(self, x, y):\n        self.x = x\n        self.y = y\n        self.vx = 5   # Moving right at 5 pixels/frame\n        self.vy = -3  # Moving up at 3 pixels/frame\n    \n    def update(self):\n        \"\"\"Update position based on velocity\"\"\"\n        self.x += self.vx\n        self.y += self.vy\n        \n    def __str__(self):\n        return f\"Position: ({self.x:.1f}, {self.y:.1f})\"\n\n# Create object and simulate 5 frames\nobj = SimpleObject(100, 100)\nprint(\"Starting:\", obj)\n\nfor frame in range(1, 6):\n    obj.update()\n    print(f\"Frame {frame}:\", obj)\n\nprint(f\"\\nTotal distance moved: X={obj.vx * 5}, Y={obj.vy * 5}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nStarting: Position: (100.0, 100.0)\nFrame 1: Position: (105.0, 97.0)\nFrame 2: Position: (110.0, 94.0)\nFrame 3: Position: (115.0, 91.0)\nFrame 4: Position: (120.0, 88.0)\nFrame 5: Position: (125.0, 85.0)\n\nTotal distance moved: X=25, Y=-15\n```\n:::\n:::\n\n\n::: {.callout-important}\n## 📖 What The Output Tells Us\n\n**Reading the results:**\n- **Starting:** (100.0, 100.0)\n- **Frame 1:** (105.0, 97.0) - moved 5 right, 3 up\n- **Frame 2:** (110.0, 94.0) - moved another 5 right, 3 up\n- **Frame 5:** (125.0, 85.0) - total of 25 right, 15 up\n\n**How it works:**\n1. Each `update()` call adds velocity to position\n2. Positive vx (+5) moves right, negative vy (-3) moves up\n3. After 5 frames: x increased by 25 (5×5), y decreased by 15 (3×5)\n\n**Real game example:** This is how a bouncing ball or flying bird moves across the screen! The game calls `update()` 60 times per second, creating smooth motion.\n\n**Try mentally:** If vx was 10, where would x be after 5 frames?\n:::\n\n::: {.callout-consider}\n## 🤔 Consider This Corner\n\n**Why use negative velocity for \"up\"?**\n\nRemember from Day 01: In Pygame, Y=0 is at the **top** of the screen, and Y increases **downward**. So to move up, we need negative Y velocity!\n:::\n\n### What is Acceleration?\n\n**Acceleration** is the change in velocity over time. Gravity is a constant downward acceleration!\n\n::: {.callout-note}\n## 🌎 Understanding Gravity in Code\n\nGravity is what makes objects fall! In our simulation:\n1. **Start with zero velocity** - object isn't moving yet\n2. **Each frame, gravity increases velocity** - the object speeds up\n3. **Velocity changes position** - the faster it falls, the more distance it covers\n\n**Real world:** When you drop a ball, it starts slow but gets faster as it falls. That's acceleration!\n:::\n\n::: {#7eb88cc9 .cell execution_count=2}\n``` {.python .cell-code}\n# Simulating gravity\n# Watch how velocity increases over time, making the object fall faster!\n\nclass FallingObject:\n    def __init__(self, x, y):\n        self.x = x\n        self.y = y\n        self.vy = 0  # Start with no velocity\n        self.gravity = 0.5  # Acceleration due to gravity\n    \n    def update(self):\n        \"\"\"Apply gravity and update position\"\"\"\n        self.vy += self.gravity  # Velocity increases\n        self.y += self.vy        # Position changes by velocity\n        \n    def __str__(self):\n        return f\"Y: {self.y:.1f}, Velocity: {self.vy:.1f}\"\n\n# Simulate falling for 10 frames\nobj = FallingObject(0, 0)\nprint(\"Falling object:\")\nfor frame in range(10):\n    print(f\"Frame {frame}: {obj}\")\n    obj.update()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nFalling object:\nFrame 0: Y: 0.0, Velocity: 0.0\nFrame 1: Y: 0.5, Velocity: 0.5\nFrame 2: Y: 1.5, Velocity: 1.0\nFrame 3: Y: 3.0, Velocity: 1.5\nFrame 4: Y: 5.0, Velocity: 2.0\nFrame 5: Y: 7.5, Velocity: 2.5\nFrame 6: Y: 10.5, Velocity: 3.0\nFrame 7: Y: 14.0, Velocity: 3.5\nFrame 8: Y: 18.0, Velocity: 4.0\nFrame 9: Y: 22.5, Velocity: 4.5\n```\n:::\n:::\n\n\n::: {.callout-important}\n## 📖 Analyzing the Falling Motion\n\n**What the numbers show:**\n- **Frame 0:** Y=0.0, Velocity=0.0 (not moving yet)\n- **Frame 1:** Y=0.5, Velocity=0.5 (started falling slowly)\n- **Frame 2:** Y=1.5, Velocity=1.0 (falling faster - velocity doubled!)\n- **Frame 9:** Y=22.5, Velocity=4.5 (really fast now)\n\n**The pattern:**\n1. Velocity increases by 0.5 each frame (that's our gravity value)\n2. As velocity increases, position changes more each frame\n3. This creates **accelerating motion** - getting faster over time\n\n**How the code does it:**\n```python\nself.vy += self.gravity  # Add 0.5 to velocity each frame\nself.y += self.vy         # Move by current velocity\n```\n\n**Real game use:** This makes jumping feel realistic - your character slows down as they go up, then speeds up as they fall back down!\n:::\n\nNotice how the velocity increases each frame, making the object fall faster and faster!\n\n### Understanding Friction and Energy Loss\n\nWhen a ball bounces, it doesn't bounce back to the same height because it loses energy. We simulate this with a **friction coefficient**.\n\n::: {.callout-note}\n## ⚽ How Bouncing Works\n\nIn real life, balls lose energy when they hit the ground:\n- Some energy becomes **sound** (the bounce noise)\n- Some becomes **heat** (friction)\n- The rest stays as **motion energy**\n\nWe use a **friction value of 0.8** meaning the ball keeps 80% of its energy each bounce (loses 20%).\n\n**Watch how:** Each bounce has less velocity than the last!\n:::\n\n::: {#d573cebc .cell execution_count=3}\n``` {.python .cell-code}\n# Simulating bouncing with energy loss\n# Each bounce will be weaker than the last\n\ndef simulate_bounce(initial_velocity, num_bounces=5):\n    \"\"\"Simulate a bouncing ball\"\"\"\n    velocity = initial_velocity\n    height = 0\n    friction = 0.8  # Ball loses 20% energy per bounce\n    \n    print(f\"Starting velocity: {velocity}\")\n    print(\"-\" * 40)\n    \n    for bounce in range(1, num_bounces + 1):\n        # Bounce: reverse direction and apply friction\n        velocity = -velocity * friction\n        print(f\"Bounce {bounce}: velocity = {velocity:.2f}\")\n    \n    print(\"-\" * 40)\n    print(f\"Final velocity: {velocity:.2f}\")\n    print(f\"Energy remaining: {(velocity/initial_velocity)*100:.1f}%\")\n\nsimulate_bounce(-15)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nStarting velocity: -15\n----------------------------------------\nBounce 1: velocity = 12.00\nBounce 2: velocity = -9.60\nBounce 3: velocity = 7.68\nBounce 4: velocity = -6.14\nBounce 5: velocity = 4.92\n----------------------------------------\nFinal velocity: 4.92\nEnergy remaining: -32.8%\n```\n:::\n:::\n\n\nThe ball keeps bouncing but each bounce is weaker!\n\n---\n\n## 🎨 Part 2: Building the Bouncing Ball Simulator (25 minutes)\n\n### Step 1: Set Up the Project\n\nFirst, let's understand our constants:\n\n```python\nimport pygame\nimport sys\nimport random\n\n# Initialize Pygame\npygame.init()\n\n# Constants\nWINDOW_WIDTH = 800\nWINDOW_HEIGHT = 600\nFPS = 60\n\n# Colors\nWHITE = (255, 255, 255)\nBLACK = (0, 0, 0)\nRED = (255, 100, 100)\nBLUE = (100, 150, 255)\nGREEN = (100, 255, 150)\nPURPLE = (200, 100, 255)\nYELLOW = (255, 255, 100)\nORANGE = (255, 165, 100)\n\nCOLORS = [RED, BLUE, GREEN, PURPLE, YELLOW, ORANGE]\n\n# Physics constants\nGRAVITY = 0.5              # Acceleration (pixels/frame²)\nFRICTION = 0.99            # Energy kept after bounce (99%)\nMIN_BOUNCE_VELOCITY = 0.5  # Stop bouncing if too slow\n```\n\n::: {.callout-tip}\n## 💡 Pro Tip\n\nNotice `FRICTION = 0.99` means the ball keeps 99% of its energy. Try different values:\n- `1.0` = Perfect bounce (no energy loss)\n- `0.8` = Bouncy ball (loses 20% energy)\n- `0.5` = Clay ball (loses 50% energy)\n:::\n\n### Step 2: Create the Ball Class\n\n```python\nclass Ball:\n    \"\"\"Represents a bouncing ball with physics.\"\"\"\n    \n    def __init__(self, x, y, radius, color):\n        \"\"\"\n        Initialize a ball.\n        \n        Args:\n            x: Initial x position\n            y: Initial y position\n            radius: Ball radius\n            color: Ball color (RGB tuple)\n        \"\"\"\n        self.x = x\n        self.y = y\n        self.radius = radius\n        self.color = color\n        \n        # Velocity (speed and direction)\n        self.vx = random.uniform(-10, 10)  # Random horizontal\n        self.vy = random.uniform(-15, -5)  # Launch upward\n```\n\nThe ball starts with:\n- Random horizontal velocity (left or right)\n- Negative vertical velocity (shoots upward)\n\n### Step 3: Implement Physics Update\n\nThis is where the magic happens!\n\n```python\n    def update(self):\n        \"\"\"Update ball position and apply physics.\"\"\"\n        # STEP 1: Apply gravity\n        self.vy += GRAVITY\n        \n        # STEP 2: Update position based on velocity\n        self.x += self.vx\n        self.y += self.vy\n        \n        # STEP 3: Bounce off left and right walls\n        if self.x - self.radius <= 0:\n            self.x = self.radius\n            self.vx = abs(self.vx) * FRICTION\n        elif self.x + self.radius >= WINDOW_WIDTH:\n            self.x = WINDOW_WIDTH - self.radius\n            self.vx = -abs(self.vx) * FRICTION\n        \n        # STEP 4: Bounce off floor\n        if self.y + self.radius >= WINDOW_HEIGHT:\n            self.y = WINDOW_HEIGHT - self.radius\n            \n            # Only bounce if moving fast enough\n            if abs(self.vy) > MIN_BOUNCE_VELOCITY:\n                self.vy = -abs(self.vy) * FRICTION\n            else:\n                self.vy = 0  # Stop bouncing\n                \n            # Apply friction to horizontal movement\n            self.vx *= 0.95\n        \n        # STEP 5: Bounce off ceiling\n        if self.y - self.radius <= 0:\n            self.y = self.radius\n            self.vy = abs(self.vy) * FRICTION\n```\n\n::: {.callout-consider}\n## 🤔 Consider This Corner\n\n**Why do we use `abs(self.vy)` when bouncing?**\n\n`abs()` makes the number positive. When hitting the floor, we want the ball to go up (negative vy), so we make it positive and then negate it: `-abs(self.vy)`.\n\nWhen hitting the right wall, we want it to go left (negative vx), so we make it positive: `abs(self.vx)`.\n\nThis ensures the ball always bounces in the correct direction!\n:::\n\n### Step 4: Draw the Ball with Velocity Vector\n\n```python\n    def draw(self, surface):\n        \"\"\"Draw the ball on the given surface.\"\"\"\n        # Draw the ball\n        pygame.draw.circle(surface, self.color, \n                          (int(self.x), int(self.y)), \n                          self.radius)\n        \n        # Draw velocity vector (shows movement direction)\n        end_x = int(self.x + self.vx * 3)\n        end_y = int(self.y + self.vy * 3)\n        pygame.draw.line(surface, WHITE, \n                        (int(self.x), int(self.y)), \n                        (end_x, end_y), 2)\n```\n\nThe white line shows which way the ball is moving and how fast!\n\n### Step 5: Create the Main Game Loop\n\n```python\ndef main():\n    \"\"\"Main game loop.\"\"\"\n    # Create window\n    screen = pygame.display.set_mode((WINDOW_WIDTH, WINDOW_HEIGHT))\n    pygame.display.set_caption(\"Day 02: Bouncing Ball Physics\")\n    \n    # Create clock\n    clock = pygame.time.Clock()\n    \n    # List to store all balls\n    balls = []\n    \n    # Create some initial balls\n    for _ in range(5):\n        x = random.randint(50, WINDOW_WIDTH - 50)\n        y = random.randint(50, 200)\n        radius = random.randint(15, 40)\n        color = random.choice(COLORS)\n        balls.append(Ball(x, y, radius, color))\n    \n    # Font for instructions\n    font = pygame.font.Font(None, 36)\n    \n    # Main game loop\n    running = True\n    while running:\n        # Handle events\n        for event in pygame.event.get():\n            if event.type == pygame.QUIT:\n                running = False\n            \n            # Add ball on mouse click\n            elif event.type == pygame.MOUSEBUTTONDOWN:\n                x, y = event.pos\n                radius = random.randint(15, 40)\n                color = random.choice(COLORS)\n                balls.append(Ball(x, y, radius, color))\n        \n        # Update all balls\n        for ball in balls:\n            ball.update()\n        \n        # Draw everything\n        screen.fill(BLACK)\n        \n        # Draw all balls\n        for ball in balls:\n            ball.draw(screen)\n        \n        # Draw instructions\n        text = font.render(\"Click to add balls!\", True, WHITE)\n        screen.blit(text, (10, 10))\n        \n        # Update display\n        pygame.display.flip()\n        clock.tick(FPS)\n    \n    pygame.quit()\n    sys.exit()\n\nif __name__ == \"__main__\":\n    main()\n```\n\n---\n\n## 🎮 Try It Yourself!\n\n### Complete Code\n\nCreate a new file `bouncing_ball.py` and copy the complete code from above, or use the provided template!\n\n### Running Your Game\n\n```bash\ncd Day_02\nuv sync\nuv run python src_instr/bouncing_ball.py\n```\n\n### What to Expect\n\n- Multiple colorful balls bouncing around\n- Each ball has a white line showing its velocity\n- Click anywhere to spawn new balls!\n- Balls gradually slow down due to friction\n\n---\n\n## 🧪 Understanding the Physics\n\n### Gravity Simulation\n\n::: {#d3b3a6fb .cell execution_count=4}\n``` {.python .cell-code}\n# Let's simulate different gravity values\n\ndef test_gravity(gravity, frames=20):\n    \"\"\"Test how objects fall with different gravity\"\"\"\n    y = 0\n    vy = 0\n    \n    print(f\"\\nGravity = {gravity}\")\n    print(\"Frame | Y Position | Velocity\")\n    print(\"-\" * 35)\n    \n    for frame in range(frames):\n        if frame % 5 == 0:  # Print every 5th frame\n            print(f\"{frame:5} | {y:10.1f} | {vy:8.2f}\")\n        vy += gravity\n        y += vy\n\n# Test different gravity values\ntest_gravity(0.5)   # Our game's gravity\ntest_gravity(1.0)   # Double gravity\ntest_gravity(0.25)  # Moon gravity!\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nGravity = 0.5\nFrame | Y Position | Velocity\n-----------------------------------\n    0 |        0.0 |     0.00\n    5 |        7.5 |     2.50\n   10 |       27.5 |     5.00\n   15 |       60.0 |     7.50\n\nGravity = 1.0\nFrame | Y Position | Velocity\n-----------------------------------\n    0 |        0.0 |     0.00\n    5 |       15.0 |     5.00\n   10 |       55.0 |    10.00\n   15 |      120.0 |    15.00\n\nGravity = 0.25\nFrame | Y Position | Velocity\n-----------------------------------\n    0 |        0.0 |     0.00\n    5 |        3.8 |     1.25\n   10 |       13.8 |     2.50\n   15 |       30.0 |     3.75\n```\n:::\n:::\n\n\n### Velocity Over Time\n\n::: {#107fc47a .cell execution_count=5}\n``` {.python .cell-code}\nimport matplotlib.pyplot as plt\n\n# Simulate a bouncing ball\ndef simulate_bouncing_ball(initial_vy=-15, friction=0.8, gravity=0.5, frames=100):\n    \"\"\"Simulate and plot ball position over time\"\"\"\n    y_positions = []\n    velocities = []\n    y = 300  # Start at middle\n    vy = initial_vy\n    \n    for _ in range(frames):\n        # Apply gravity\n        vy += gravity\n        y += vy\n        \n        # Bounce off ground (y=600)\n        if y >= 600:\n            y = 600\n            vy = -abs(vy) * friction\n        \n        y_positions.append(y)\n        velocities.append(vy)\n    \n    # Create plots\n    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 6))\n    \n    # Plot position\n    ax1.plot(y_positions, color='blue', linewidth=2)\n    ax1.set_ylabel('Y Position (pixels)')\n    ax1.set_title('Ball Position Over Time')\n    ax1.invert_yaxis()  # Flip so down is positive\n    ax1.grid(True, alpha=0.3)\n    \n    # Plot velocity\n    ax2.plot(velocities, color='red', linewidth=2)\n    ax2.set_xlabel('Frame')\n    ax2.set_ylabel('Velocity (pixels/frame)')\n    ax2.set_title('Ball Velocity Over Time')\n    ax2.axhline(y=0, color='black', linestyle='--', alpha=0.3)\n    ax2.grid(True, alpha=0.3)\n    \n    plt.tight_layout()\n    plt.show()\n    \n    return y_positions, velocities\n\n# Run simulation\npositions, velocities = simulate_bouncing_ball()\nprint(f\"Ball bounced {sum(1 for v in velocities if v < 0 and velocities[velocities.index(v)-1] > 0)} times\")\n```\n\n::: {.cell-output .cell-output-display}\n![](day02_tutorial_files/figure-html/cell-6-output-1.png){width=950 height=566}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nBall bounced 1 times\n```\n:::\n:::\n\n\nNotice how the bounces get smaller and smaller!\n\n---\n\n## 🎯 Challenges\n\n### 🌟 Easy Challenges\n\n1. **Change Gravity**: Make gravity stronger (1.0) or weaker (0.25)\n2. **Modify Friction**: Make balls bouncier (0.95) or less bouncy (0.7)\n3. **Add More Colors**: Create new color options\n\n### 🌟🌟 Medium Challenges\n\n4. **Add Ball Collisions**: Make balls bounce off each other\n5. **Size Matters**: Make smaller balls bounce higher than large ones\n6. **Wind Effect**: Add horizontal force to simulate wind\n\n### 🌟🌟🌟 Hard Challenges\n\n7. **Trail Effect**: Show the path balls have traveled\n8. **Energy Display**: Show total energy in the system\n9. **Sticky Floor**: Make balls stick after bouncing a few times\n\n---\n\n## 💡 Code Variations to Try\n\n### Different Ball Behaviors\n\n```python\n# Super bouncy ball\nFRICTION = 1.0\nMIN_BOUNCE_VELOCITY = 0\n\n# Heavy ball (less bouncy)\nFRICTION = 0.6\nGRAVITY = 0.8\n\n# Moon physics\nGRAVITY = 0.1\nFRICTION = 0.95\n```\n\n### Random Spawn Positions\n\n```python\n# In main(), instead of clicking, spawn balls automatically\nimport time\n\nlast_spawn_time = time.time()\n\n# In game loop:\ncurrent_time = time.time()\nif current_time - last_spawn_time > 0.5:  # Every 0.5 seconds\n    x = random.randint(50, WINDOW_WIDTH - 50)\n    y = 50\n    radius = random.randint(15, 40)\n    color = random.choice(COLORS)\n    balls.append(Ball(x, y, radius, color))\n    last_spawn_time = current_time\n```\n\n---\n\n## 📚 Key Terms to Remember\n\n- **Velocity**: Speed and direction of movement\n- **Acceleration**: Rate of change of velocity (gravity is constant acceleration)\n- **Gravity**: Downward acceleration (makes things fall)\n- **Friction/Restitution**: Energy loss during collisions\n- **Vector**: A quantity with both magnitude (size) and direction\n- **Frame**: One update cycle of the game (60 FPS = 60 updates/second)\n\n---\n\n## 🔬 Physics Fun Facts\n\n::: {.callout-consider}\n## 🤔 Real World Physics\n\n**Did you know?**\n\n- On Earth, gravity accelerates objects at 9.8 m/s² (about 32 ft/s²)\n- On the Moon, gravity is only 1.62 m/s² (about 1/6 of Earth's)\n- A real tennis ball has a coefficient of restitution around 0.75\n- No ball bounces perfectly (friction = 1.0) due to energy loss to heat and sound!\n\nIn our game, 1 pixel/frame² is like our unit of \"game gravity\". Try different values to simulate different planets!\n:::\n\n---\n\n## 💡 Tips for Better Physics Games\n\n1. **Keep Frame Rate Consistent**: Use `clock.tick(FPS)` to ensure smooth physics\n2. **Start with Simple Physics**: Get basic movement working before adding complexity\n3. **Use Small Gravity Values**: Large values make movement look unrealistic\n4. **Test Edge Cases**: What happens with very large velocities? Very small balls?\n5. **Visual Feedback**: The velocity vectors help debug physics issues\n\n---\n\n## 🏁 Wrapping Up\n\nAmazing work! You've created a physics simulation with realistic bouncing, gravity, and friction. You now understand how games create realistic movement!\n\n### What You Accomplished\n\n✅ Implemented velocity and acceleration  \n✅ Created gravity simulation  \n✅ Built realistic bouncing with energy loss  \n✅ Managed multiple objects  \n✅ Added interactive spawning  \n\n### What's Coming Next?\n\n**Day 03: Pong Game** - We'll use our physics knowledge to create a classic two-player game with paddles and a ball!\n\n::: {.callout-important}\n## 📝 Homework (Optional)\n\nBefore Day 03:\n1. Experiment with different friction and gravity values\n2. Try adding wind (constant horizontal acceleration)\n3. Create a \"pool table\" simulation with multiple balls\n4. Make balls change color when they bounce\n:::\n\n---\n\n## � Complete Code - Ready to Copy!\n\n```python\n\"\"\"\nDay 02: Bouncing Ball Physics - Complete Working Version\n\"\"\"\n\nimport pygame\nimport sys\nimport random\n\npygame.init()\n\nWINDOW_WIDTH = 800\nWINDOW_HEIGHT = 600\nFPS = 60\n\nWHITE = (255, 255, 255)\nBLACK = (0, 0, 0)\nRED = (255, 100, 100)\nBLUE = (100, 150, 255)\nGREEN = (100, 255, 150)\nPURPLE = (200, 100, 255)\nYELLOW = (255, 255, 100)\nORANGE = (255, 165, 100)\n\nCOLORS = [RED, BLUE, GREEN, PURPLE, YELLOW, ORANGE]\n\nGRAVITY = 0.5\nFRICTION = 0.99\nMIN_BOUNCE_VELOCITY = 0.5\n\n\nclass Ball:\n    def __init__(self, x, y, radius, color):\n        self.x = x\n        self.y = y\n        self.radius = radius\n        self.color = color\n        self.vx = random.uniform(-10, 10)\n        self.vy = random.uniform(-15, -5)\n        \n    def update(self):\n        self.vy += GRAVITY\n        self.x += self.vx\n        self.y += self.vy\n        \n        if self.x - self.radius <= 0:\n            self.x = self.radius\n            self.vx = abs(self.vx) * FRICTION\n        elif self.x + self.radius >= WINDOW_WIDTH:\n            self.x = WINDOW_WIDTH - self.radius\n            self.vx = -abs(self.vx) * FRICTION\n        \n        if self.y + self.radius >= WINDOW_HEIGHT:\n            self.y = WINDOW_HEIGHT - self.radius\n            if abs(self.vy) > MIN_BOUNCE_VELOCITY:\n                self.vy = -abs(self.vy) * FRICTION\n            else:\n                self.vy = 0\n            self.vx *= 0.95\n        \n        if self.y - self.radius <= 0:\n            self.y = self.radius\n            self.vy = abs(self.vy) * FRICTION\n            \n    def draw(self, surface):\n        pygame.draw.circle(surface, self.color, (int(self.x), int(self.y)), self.radius)\n        end_x = int(self.x + self.vx * 3)\n        end_y = int(self.y + self.vy * 3)\n        pygame.draw.line(surface, WHITE, (int(self.x), int(self.y)), (end_x, end_y), 2)\n\n\ndef main():\n    screen = pygame.display.set_mode((WINDOW_WIDTH, WINDOW_HEIGHT))\n    pygame.display.set_caption(\"Day 02: Bouncing Ball Physics\")\n    clock = pygame.time.Clock()\n    \n    balls = []\n    for _ in range(5):\n        x = random.randint(50, WINDOW_WIDTH - 50)\n        y = random.randint(50, 200)\n        radius = random.randint(15, 40)\n        color = random.choice(COLORS)\n        balls.append(Ball(x, y, radius, color))\n    \n    font = pygame.font.Font(None, 36)\n    \n    running = True\n    while running:\n        for event in pygame.event.get():\n            if event.type == pygame.QUIT:\n                running = False\n            elif event.type == pygame.MOUSEBUTTONDOWN:\n                x, y = event.pos\n                radius = random.randint(15, 40)\n                color = random.choice(COLORS)\n                balls.append(Ball(x, y, radius, color))\n        \n        for ball in balls:\n            ball.update()\n        \n        screen.fill(BLACK)\n        for ball in balls:\n            ball.draw(screen)\n        \n        text = font.render(\"Click to add balls!\", True, WHITE)\n        screen.blit(text, (10, 10))\n        \n        pygame.display.flip()\n        clock.tick(FPS)\n    \n    pygame.quit()\n    sys.exit()\n\n\nif __name__ == \"__main__\":\n    main()\n```\n\n---\n\n## �📖 Additional Resources\n\n- [Physics in Games (Khan Academy)](https://www.khanacademy.org/computing/computer-programming/programming-games-visualizations)\n- [Pygame Physics Tutorial](https://www.pygame.org/wiki/tutorials)\n- [Understanding Velocity and Acceleration](https://www.khanacademy.org/science/physics/one-dimensional-motion)\n\n---\n\n::: {.hero-banner}\n# See you on Day 03! 🏓\n\nYou're becoming a game developer! Keep experimenting and having fun!\n\n*\"Physics is like sex: sure, it may give some practical results, but that's not why we do it.\"* - Richard Feynman\n:::\n\n",
    "supporting": [
      "day02_tutorial_files/figure-html"
    ],
    "filters": [],
    "includes": {}
  }
}